var buttonColours = ["red", "blue", "green", "yellow"];

var userClickedPattern = [];  //Stores each color of User clicked Buttons
var gamePattern = [];  //Stores each random color generated by the game

var isStarted = false;
var level = 0;

//onKeyPress
$(document).keypress(function (){
    if(!isStarted){    //Initial Play
        nextSequence();
        isStarted = true;
        $("#level-title").text("Level "+ level);
    }
})

//Verifies the GamePlay
function checkAnswer(currentLevel){
    if(userClickedPattern[currentLevel]===gamePattern[currentLevel]){
        if(userClickedPattern.length === gamePattern.length){
            setTimeout(function(){
                nextSequence();
            }, 1000);
        }
    }
    else{
        playSound("wrong");
        $("body").addClass("game-over");
        setTimeout(function(){
            $("body").removeClass("game-over");
        }, 200);
        $("#level-title").text("Game Over, Press Any Key to Restart");
        startOver();
    }
}

//Creates a next random colour sequence to play with
function nextSequence(){
    userClickedPattern = [];
    level++;
    $("#level-title").text("Level "+ level);
    var randomNumber = Math.floor(Math.random()*4);
    var randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);

    $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);
}

//User Button Game Play
$(".btn").click(handler);
function handler(){
    var userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);

    playSound(userChosenColour);
    animatePress(userChosenColour);
    
    checkAnswer(userClickedPattern.length-1);
    
}

//Animates each Button's Behaviour
function animatePress(currentColour){
    $("#" + currentColour).addClass("pressed");
    setTimeout(function(){
        $("#"+ currentColour).removeClass("pressed");
    }, 100);
}

//Plays the respective audio files
function playSound(name){
    var audio = new Audio("sounds/" + name + ".mp3");
    audio.play();
}

//Restarts the game, if it is over
function startOver() {
    level = 0;
    gamePattern = [];
    isStarted = false;
  }